# Use the official PostgreSQL image from the Docker Hub
FROM postgres:17-alpine3.20

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=library_jooq

# Copy the SQL dump file into the container
COPY library_dump.sql /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
EXPOSE 5432