services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_jooq
    ports:
      - "5566:5432"
    volumes: # volume used to persist data
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: library-go
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - db
    ports:
      - "7070:7070"
    environment:
      DOCKER_ENV: true
      DB_URL_CONTAINER: postgres://postgres:postgres@db:5432/library_jooq

volumes:
  pgdata: {}